---
title: "writing_functions"
author: "Ruiqi Yan"
date: "11/4/2021"
output: github_document
---

```{r}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Z scores


```{r}
x_vec = rnorm(25, mean = 5, sd = 4)
y_vec = rnorm(25, mean = 10, sd = 4)

(x_vec - mean(x_vec)) / sd(x_vec)

z_scores <- function(x) {
  
  z = (x - mean(x)) / sd(x)
  
  return(z)
  
}

z_scores(x = x_vec)
```

How great is it?

Let's try again

```{r}
z_scores <- function(x) {
  if(!is.numeric(x)){
    stop("Argument x should be numeric")
  }
  
  if(length(x) < 3){
    stop("Z scores cannot be computed for length 1 vectors")
  }
  z = (x - mean(x)) / sd(x)
  
  return(z)
  
}
```


```{r error = TRUE}
z_scores(3)

z_scores("my", "name", "is", "jeff")

z_scores(mtcars)
```


## Multiple outputs

```{r}
mean_and_sd <- function(x) {
  if(!is.numeric(x)){
    stop("Argument x should be numeric")
  }
  
  if(length(x) < 3){
    stop("Z scores cannot be computed for length 1 vectors")
  }
  mean_x <- mean(x)
  sd_x <- sd(x)
  
  output_df <- 
    tibble(
      mean = mean_x,
      sd = sd_x
    )
  return(output_df)
  
}

mean_and_sd(x_vec)
```


## Different smaple sizes, means, sds


```{r}
sim_data <- tibble(
  x = rnorm(30, mean = 2, sd = 3)
)

sim_data %>% 
  summarize(
    mean = mean(x),
    sd = sd(x)
  )


```

Let's write a function that simulates data, computes the mean and sd.

```{r}
sim_mean_sd = function(n, mu = 3, sigma = 4){
  
  sim_data <- tibble(
  x = rnorm(n, mean = mu, sd = sigma)
  )
  
  sim_data %>% 
    summarize(
      mean = mean(x),
      sd = sd(x)
    )
}

sim_mean_sd(30, 4, 3)

sim_mean_sd(30)
```

